### PR TITLE
Created responsive navigation bar

### LINKED ISSUE #20: Navbar UI
**Description**
Create a top navigation bar that contains Home, Explore, and My Cookbooks navigation buttons

**Issue Points**: 1

### PR DESCRIPTION
**Pull request by minhdinh901**
Resolves #20 

**Description**

Here is a video showing the functionality of the navbar

https://user-images.githubusercontent.com/31702110/140909080-c0429891-84ba-4fb3-820b-8d273a08ac75.mp4

**UPDATE**: The tabs for the desktop (landscape) view are now left justified instead of centered like in the above video.

left-justified-desktop

### CODE REVIEW

**Review by grantDuntugan — APPROVED** [review]
Looks good! I'm not sure if the tabs would look nicer in the center or left-justified, but I'm fine with the way it is now.

**Comment by minhdinh901** [comment]
> Looks good! I'm not sure if the tabs would look nicer in the center or left-justified, but I'm fine with the way it is now.

Left justified for desktop view or for mobile view?

**Comment by grantDuntugan** [comment]
> > Looks good! I'm not sure if the tabs would look nicer in the center or left-justified, but I'm fine with the way it is now.
> 
> Left justified for desktop view or for mobile view?

For desktop view. I think the mobile view is nice centered because of the small screen width, but I think on longer screen widths it may be more standard to have left justified. Maybe because you don't have to move your mouse as much. 

For example the github navbar:

github nav

**Comment by minhdinh901** [comment]
> > > Looks good! I'm not sure if the tabs would look nicer in the center or left-justified, but I'm fine with the way it is now.
> > 
> > 
> > Left justified for desktop view or for mobile view?
> 
> For desktop view. I think the mobile view is nice centered because of the small screen width, but I think on longer screen widths it may be more standard to have left justified. Maybe because you don't have to move your mouse as much.
> 
> For example the github navbar:
> 
> github nav
Here's a left justified navbar that I quickly modified
left-justified

**Comment by grantDuntugan** [comment]
> > > > Looks good! I'm not sure if the tabs would look nicer in the center or left-justified, but I'm fine with the way it is now.
> > > 
> > > 
> > > Left justified for desktop view or for mobile view?
> > 
> > 
> > For desktop view. I think the mobile view is nice centered because of the small screen width, but I think on longer screen widths it may be more standard to have left justified. Maybe because you don't have to move your mouse as much.
> > For example the github navbar:
> > github nav
> 
> Here's a left justified navbar that I quickly modified left-justified

Yeah, that looks good! I think we can add icons later, but for now I like it.

**Review by grantDuntugan — APPROVED** [review]

**Review by keli214 — COMMENTED** [review]
Look great!

**Review by keli214 — APPROVED** [review]

**Pull request merged**
