### PR TITLE
Recipe form

### PR DESCRIPTION
**Pull request by YelllowBelly**
Video Below:

https://user-images.githubusercontent.com/72407494/141400296-bc51cbfc-5820-4444-8755-703ae7643f2d.mov

New Button sizes:

Screen Shot 2021-11-11 at 6 55 46 PM
Screen Shot 2021-11-11 at 6 55 56 PM

### CODE REVIEW

**Comment by grantDuntugan** [comment]
Is it possible to increase the height of the add ingredients and add instructions button? And also reduce the height and increase the width of the save ingredients button? Thanks!

**Review by grantDuntugan — APPROVED** [review]

**Comment by minhdinh901** [comment]
Why are there a lot of files in the `img` folder? Also, you can remove the bottom wave, it is a separate component now. Also, the form behaves strangely when I put the webpage into iphone X dimensions, specifically, the button text becomes misaligned.

**Comment by YelllowBelly** [comment]
> Why are there a lot of files in the `img` folder? Also, you can remove the bottom wave, it is a separate component now. Also, the form behaves strangely when I put the webpage into iphone X dimensions, specifically, the button text becomes misaligned.

**Comment by YelllowBelly** [comment]
I can remove the unused images it was from when I ported the design from figma. I will also remove the wave and fix the iphone compataibility

**Pull request closed without merging**
