### PR TITLE
Created recipe page UI

### LINKED ISSUE #24: Recipe Page UI
**Description**
Create the recipe page. Add spaces for everything you see in Figma. Author, published by, tags, picture, description, ingredients, instructions, etc. Also have edit and delete buttons if it's a saved recipe. Don't do the top nav bar!! Don't worry about the information either! Test with dummy values.

**Issue Points**: 2

### PR DESCRIPTION
**Pull request by minhdinh901**
Resolves #24 

**Description**

Here is a video of the recipe page functionality

https://user-images.githubusercontent.com/31702110/141244631-bcd76747-5102-4979-a9cc-2b29b42cbe92.mp4

### CODE REVIEW

**Review by grantDuntugan — COMMENTED** [review]
What happens to the recipe text-wrap if you put a super long recipe?

**Comment by minhdinh901** [comment]
> What happens to the recipe text-wrap if you put a super long recipe?

Do you mean a super long description or ingredient or instruction?

**Review by keli214 — APPROVED** [review]

**Comment by grantDuntugan** [comment]
> > What happens to the recipe text-wrap if you put a super long recipe?
> 
> Do you mean a super long description or ingredient or instruction?

A super long ingredient, my bad. Something like "A half tablespoon of vanilla extract (optionally, could use up to a tablespoon for extra sweetness"

**Comment by minhdinh901** [comment]
> > > What happens to the recipe text-wrap if you put a super long recipe?
> > 
> > 
> > Do you mean a super long description or ingredient or instruction?
> 
> A super long ingredient, my bad. Something like "A half tablespoon of vanilla extract (optionally, could use up to a tablespoon for extra sweetness"

It would look like this

long-ingredient

**Review by grantDuntugan — APPROVED** [review]
Cool, looks good!

**Pull request merged**
